sonar.projectKey=simulador-mundial-2026
sonar.projectName=Simulador Mundial 2026
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=tests/**,allure-results/**,allure-report/**,**/__pycache__/**
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
